### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by MattBSG** [remyjette/PAXSchedule#13]
The certificate on the production site has been expired for about 90 days now

**Comment by remyjette** [comment]
Thanks for the heads up! Looks like my notification settings for this repo weren't set (now fixed).

The Azure extension I was using to talk to LetsEncrypt was throwing NullReferenceExceptions when trying to renew the cert. https://github.com/sjkp/letsencrypt-siteextension/issues/365

I've moved to a different method (https://github.com/shibayan/keyvault-acmebot), let's see if this is more reliable with auto-renew...
